@startuml
'namespace EtAlii.BinanceMagic.Service
'class EdgeSequence
'generate partial

title Automatic trading mechanism B: Edge.

state InitialPurchase

[*] --> InitialPurchase : Start
InitialPurchase --> TrySell
TrySell --> [*]

@enduml