@startuml
'namespace EtAlii.CryptoMagic
'class EdgeSequence
'generate partial

title Automatic trading mechanism B: Edge.

state InitialPurchase

[*] --> InitialPurchase : Start
InitialPurchase --> TrySell : Continue
TrySell --> [*] : Continue

@enduml